before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags: -trimpath
    ldflags: '-s -w -extldflags "-static" -X github.com/tinkerbell/pbnj/server/httpsvr.GitRev={{.ShortCommit}}'
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
  - "quay.io/tinkerbell/pbnj:{{ .Version }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile.goreleaser
  extra_files:
  - scripts/etc-passwd
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/tinkerbell/pbnj:{{ .Version }}-arm64"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile.goreleaser
  extra_files:
  - scripts/etc-passwd
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
docker_manifests:
- name_template: quay.io/tinkerbell/pbnj:{{ .Version }}
  image_templates:
  - quay.io/tinkerbell/pbnj:{{ .Version }}-amd64
  - quay.io/tinkerbell/pbnj:{{ .Version }}-arm64