apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pbnj-auth
  labels:
    k8s-app: pbnj
  annotations:
    keymaker.packet.net/generate: 'true'
spec:
{{ if .Values.localDev.Enabled }}
  backendType: vault
  kvVersion: 2
{{ else }}
  backendType: systemManager
{{ end }}
  data:
{{ if .Values.localDev.Enabled }}
    - key: kubernetes/metadata/{{ .Values.env }}/{{ .Values.location }}/pbnj
{{ else }}
    - key: /{{ .Values.env }}/{{ .Values.location }}/pbnj/access-id
{{ end }}
      name: access-id
{{ if .Values.localDev.Enabled }}
    - key: kubernetes/metadata/{{ .Values.env }}/{{ .Values.location }}/pbnj
{{ else }}
    - key: /{{ .Values.env }}/{{ .Values.location }}/pbnj/access-secret
{{ end }}
      name: access-secret
